[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
celo_sepolia = "${CELO_SEPOLIA_RPC_URL}"

[etherscan]
44787 = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.celoscans.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
